# Change these first
owner: eramba # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Eramba Web
    url: https://www.eramba.org
  - name: Eramba Discussions
    url: https://discussions.eramba.org/
  - name: Demo Community Cloud
    url: https://demo.cloud.eramba.org
  - name: Demo Enterprise Cloud
    url: https://demo-e.cloud.eramba.org
  - name: Test Dead Cloud Instance
    url: https://dead.cloud.eramba.org
  - name: Test
    url: https://eramba.cloud.eramba.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#  cname: eramba.github.io
  baseUrl: /upptime
  theme: light
  logoUrl: https://raw.githubusercontent.com/eramba/upptime/master/assets/eramba-logo.svg
  name: ""
  introTitle: ""
  introMessage:
  navbar:
    #- title: Status
    #  href: /
    #- title: GitHub
  #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
