# Change these first
owner: eramba # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

workflowSchedule:
  uptime: "1,15,35,45 * * * *"

sites:
  - name: Eramba Web
    url: https://www.eramba.org/about-us
  - name: Eramba Learning
    url: https://www.eramba.org/learning
  - name: Eramba Discussions
    url: https://discussions.eramba.org/about
  - name: Eramba Download portal
    url: https://downloads.eramba.org/downloads/login
  - name: Eramba Support
    url: https://support-v3.eramba.org/ping.html
  - name: Eramba Plugins
    url: https://plugins.eramba.org
    __dangerous__body_down_if_text_missing: "This is a private Composer repository."
  - name: Demo Community Cloud
    url: https://demo.cloud.eramba.org/login
  - name: Demo Enterprise Cloud
    url: https://demo-e.cloud.eramba.org/login
  - name: Demo Enterprise Cloud API
    url: https://demo-e.cloud.eramba.org/api/projects/index
    headers:
      - "Authorization: Basic YWRtaW46YWxwaGFudW1lcmljMQ=="
      - "Content-Type: application/json"
      - "Accept: application/json"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#  cname: eramba.github.io
  baseUrl: /upptime
  theme: light
  logoUrl: https://raw.githubusercontent.com/eramba/upptime/master/assets/eramba-logo.svg
  name: ""
  introTitle: ""
  introMessage:
  navbar:
    #- title: Status
    #  href: /
    #- title: GitHub
  #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
